title: Duva
description: Strongly consistent key-value store written in Rust
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections:
  commands:
    output: true
    permalink: /commands/:name

defaults:
  - scope:
      path: ""
      type: commands
    values:
      layout: command