title: Duva
description: Strongly consistent key-value store written in Rust
url: "https://migorithm.github.io"  # The base hostname of your site
baseurl: "/duva"                   # The subpath of your site
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections:
  commands:
    output: true
    permalink: /commands/:name

defaults:
  - scope:
      path: ""
      type: commands
    values:
      layout: command