[package]
name = "duva-client"
version = "0.1.0"
edition = "2024"

[dependencies]
duva = { path = "../duva" }
clap = { version = "*", features = ["derive"] }
rustyline = { version = "15.0.0", features = [
    "rusqlite",
    "with-sqlite-history",
    "derive",
] }


[[bin]]
name = "cli"
path = "src/cli/main.rs"
# cargo run -p duva-client --bin cli -- --port 6000
