title: Duva - Distributed Cache Server
email: saka90030@gmail.com
description: >-
  Duva is a distributed cache server built for efficient and scalable key-value store operations using Actor models, written in Rust. Explore its features, architecture, and how to get started!

baseurl: "/duva" # The subpath of your site
url: "https://migorithm.github.io" # The base hostname for your site

github_username: migorithm

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Improves SEO for better search engine visibility

header_pages:

  - commands.markdown
  - about.markdown

collections:
  commands:
    output: true
    permalink: /commands/:name/

# Minima theme customizations
minima:
  
  social_links:
    - { platform: github, user_url: "https://github.com/migorithm" }
  custom_styles:
    - "/assets/css/custom.css"

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md