name: Build and push container images

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
      - "hotfix/*"
      - "fix/*"
      - "feat/*"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: ./.github/workflows/test
  build-and-push-container-images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ["duva", "duva-client"]

    needs:
      - test

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build and push duva image using kaniko
        uses: aevea/action-kaniko@master
        with:
          push: true
          registry: ghcr.io
          image: ${{ matrix.image }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: ${{ matrix.image }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
